#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
#bootstrap_before='myspacevim#before'
#bootstrap_after='myspacevim#after'
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "lunaperche"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "custom_init#before"
    #filemanager = "nerdtree"

#############################################

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "checkers"
lint_on_the_fly = true

# Enable Debugging
[[layers]]
name = 'debug'

# Edit Layer  
[[layers]]
name = 'edit'

# Emmet-vim for HTML  
#[[layers]]
#name = "lang#html"
#emmet_filetyps = ['html']


# Default Layer (for copy and paste)
[[layers]]
name = "default"
#############################################

# Custom Plugins
[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "mattn/emmet-vim"
    merged = false


# Custom Plugins
[[custom_plugins]]
    repo = "puremourning/vimspector"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "szw/vim-maximizer"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "w0rp/ale"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "vimwiki/vimwiki"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "alvan/vim-closetag"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "mlaursen/vim-react-snippets"
    merged = false

# Custom Plugins
[[custom_plugins]]
    repo = "SirVer/ultisnips"
    merged = false
##############################################
